Update model file naming to use _New suffix
Changed model file naming convention in experiment_helper.py, train_CIFAR.py, train_F_MNIST.py, train_MNIST.py and train_GTSRB.py to append '_New' to the filenames.

Old models don't work when loaded with latest tensorflow versions due to input shape dimensions mismatch
with error

ValueError: Kernel shape must have the same length as input, but received kernel of shape (5, 5, 1, 40) and input of shape (None, None, 28, 28, 1).